#!/bin/bash
COUNT=1
GRADO=""
CRED=""
TOTAL_ROW=$(wc -l $1)
PROC=$1
echo "Total lines $TOTAL_ROW"
[ "$2" = "-r" ] && CHAR="[A-Z]"
while read lin
do
  [ ! -z $(echo $lin | grep -q Legajo && echo 1)  ] && CRED=$(echo $lin | grep Legajo | egrep -o "$CHAR[0-9]{6}")
  if [ ! -z $(echo $lin | grep -q '^Categor' && echo 1) ]
  then
    #GRADO=$(echo $lin | sed -e 's/Categor?a: \(.*\) Grupo/\1/g')
    #GRADO_P=$(echo $lin | sed -e  "s/Categor?a: \\(.*\\) Grupo.*/\1/g")
    #GRADO=$(echo $GRADO_P | sed  "s/Categor?a: \(.*\) Grupo.*/\1/g")
    P=${lin##*Categor?a: }
    GRADO=${P%% Grupo*}
  fi
  #echo $CRED " " $GRADO
  if [ ! -z $(echo $lin | egrep -q '^[0-9]{6}' && echo 1) ]
  then
    CODIGO=$(echo $lin | egrep -o '^[0-9]{6}')
    IMPORTE=$(echo $lin | egrep -o '[0-9]{1,5}\.[0-9]{2}')
    echo $CRED ";" $GRADO ";" $CODIGO ";" $IMPORTE
  fi
  #echo $GRADO
  COUNT=$((COUNT +1))
  [ $((COUNT % 1000)) -eq 0 ] && echo "Progress $COUNT over $TOTAL_ROW" > parser_stat_$PROC
done < $1
