#!/bin/bash
COUNT=1
GRADO=""
CRED=""
IMPORTE=
TOTAL_ROW=$(wc -l $1)
PROC=$!

while IFS= read lin
do
  if [ ! -z $(echo "$lin" | cut -c42-48 | egrep -o "[A-Z][0-9]{6}") ]
  then
    CRED=${lin:41:7}
    GRADO=${lin:33:2}
  fi

  if [ ! -z $(echo "$lin" | cut -c4-6 | egrep -q '^[0-9]{3}' && echo 1) ]
  then
    CODIGO=${lin:3:3}
    IMPORTE=$(echo "$lin" | cut -c40-48 | tr -d ' ' )
    NEGATIVE=${lin:48:1}
    echo $CRED ";" $GRADO ";" $CODIGO ";"$NEGATIVE$IMPORTE
  fi

  COUNT=$((COUNT +1))
  [ $((COUNT % 1000)) -eq 0 ] && echo "Progress $COUNT over $TOTAL_ROW" > parser_stat_$PROC
done < $1
echo "Done $COUNT over $TOTAL_ROW" > parser_stat_$PROC
